In [6]:
import torch
import numpy as np
import pickle

In [7]:
path = 'runs/lstm_max_len_5_vocab_5_same_data_attr_4_split_2/1/'

In [4]:
# extract model state dict

# import pickle
model_path = path + 'model.p'
state = torch.load(model_path)

print(state['receiver'])

receiver_state = state['receiver']

# save this there why not
#torch.save(receiver_state, )

OrderedDict([('embedding', tensor([[-0.0030, -0.3347, -0.1467, -0.3628,  0.1390, -0.1142,  0.4853, -0.3263,
         -0.1472, -0.2310, -0.0730, -0.0210,  0.0336,  0.0875, -0.2350,  0.2192,
          0.0172, -0.1117,  0.0061,  0.2498,  0.1016, -0.3668, -0.0366, -0.0049,
         -0.4558, -0.0177,  0.0933,  0.0549,  0.0205, -0.0526,  0.1581,  0.2438,
         -0.0608, -0.0739, -0.0929, -0.1799, -0.1732, -0.3582, -0.0514, -0.1718,
         -0.0207, -0.1103,  0.0384, -0.1836, -0.2312, -0.2579,  0.0591,  0.3080,
          0.3032,  0.0451, -0.3909, -0.1855,  0.0766,  0.3273,  0.2468, -0.1293,
         -0.3623, -0.0201, -0.4257, -0.1075, -0.4349, -0.0761, -0.1739, -0.1789],
        [ 0.1047,  0.1794,  0.3388,  0.2762,  0.3053, -0.0561, -0.3870,  0.2793,
          0.0967,  0.0661,  0.3518, -0.0569, -0.0788, -0.1824,  0.3259, -0.1503,
          0.1166,  0.0971, -0.1845,  0.0518, -0.3562,  0.2064, -0.2290, -0.2720,
          0.1346,  0.0098, -0.3484,  0.1290, -0.2773, -0.0081,  0.2479, -0.1585,


In [14]:
# extract vocabulary --> use integers

vocab = pickle.load(open('data/dict_5.pckl', 'rb'))

# extract the values
vocab_i = vocab['stoi'].values()

# vocab should be an integer of 0 to 8
f = open("data/vocab.txt","w+")

for v in vocab_i:
    f.write("%d\n" % (v))

f.close()

In [25]:
# extract corpus

# start with having the messages in one line

# load the final messages from the training? or the gen? can easily alter this afterwards
messages = pickle.load(open(path+'metrics_at_10000.pkl', 'rb'))['messages']
print(messages)

# create a new file
f = open("data/corpus.txt","w+")
   
# write down the message
for message in messages:
    for char in message:
        f.write("%i " % (char))
    f.write("\n")
    
# add the target?

# close the file
f.close()

#print(messages.astype(int))

#np.savetxt("data/corpus.txt", messages.astype(int), delimiter=' ', fmt="%i");

# reload and add or customly make it by uncommenting the code above


[[6 0 2 2 2 2]
 [6 2 2 0 0 0]
 [6 2 2 2 0 0]
 ...
 [6 1 3 3 3 3]
 [6 1 3 3 3 3]
 [6 0 3 3 3 3]]
